### ISSUE TITLE
The Perfect Fuel - (26507)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2228]
**In Progress Reports**

> seems like only one battery would spawn at a time. Also a bit of quest text describing who to turn the quest back into would be helpful

> The quest tells you to go to noonshade ruins and kill trolls for batteries. At noonshade ruins there are only human wastewander bandits and they do not drop batteries

> Ancient batteries are nowhere to be seen at Noonshade Ruins

> Ancient Battery is supposed to drop from trolls at the Noonshade Ruins, but there are no trolls at the Noonshade Ruins. Killing the other spawns at the Noonshade Ruins does not yield any batteries. Other trolls around the zone also does not seem to yield any batteries. So I don't think this quest can be completed.

> The Ancient Batteries for this quest don't seem to exist at the Noonshade Ruins. Thought it was just slow respawns at first, but had mobs respawn 3 times while noone else was there and 0 batteries anywhere in the area.

> Ancient Batteries are not respawning. They seem to only spawn when the server resets, but don't respawn afterwards.

> Spawn rate is abysmal

> I can't find any Ancient Batteries in the Noonshade Ruins or dropped from the mobs there.

> Noonshade ruins contained nothing to loot or interact with and 5 bandits didnt drop batteries.

> The respawn time for the batteries is extremely long and its making the quest next to impossible to complete.

**Comment by Kestrana** [comment]
This was fixed during the Beta.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8295 Based on what Kaytotes said this isnt really fixed yet

**Comment by Bennylavaa** [comment]
Also issues with this quest unrelated to respawns:

In the quest "The Perfect Fuel" in Tanaris, even after you gathered all 8 Ancient Batteries, you can still interact and open the Ancient Troll Pots.
Although you won't get any more of the quest items, the Ancient Troll Pot will despawn.

https://github.com/Project-Epoch/bugtracker/issues/8299

**Comment by Kestrana** [comment]
Quest items not sharing with party was also fixed in beta. Did you retest
to determine this is still an issue for this quest?

**Comment by Kestrana** [comment]
Also opening quest objects after completion causing item to despawn is a
global issue not limited to this quest and should be covered under either a
core issue or generic issue.

**Comment by Bennylavaa** [comment]
> Quest items not sharing with party was also fixed in beta. Did you retest to determine this is still an issue for this quest?

Updated and corrected I was consolidating the quest issues into the specific quest. 



> Also opening quest objects after completion causing item to despawn is a global issue not limited to this quest and should be covered under either a core issue or generic issue.

Noted.
