### ISSUE TITLE
Seal of Dedication

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2993]
**Spell ID's:** 91933, 91934

> sometimes cant cast judgement with seal of dedication

> sometimes it cant use judgement

> Crits from this seal and its judgement do not proc VEngeance

> Can't twist into Seal of Dedication, presumably this is a bug. Also, this is really just a minor detail, but all other seals capitalize the word Paladin ("Fills the Paladin with...") but this one starts with "Fills the paladin with..." and this irritates me lol. I don't care which way it is, just would like the text to be consistent across all seals!

> 325 Engineering.

> Continuously doesn't allow me to use judgement with it

> If you have Seal of Righteousness already activated, then activate Seal of Dedication, you cannot cast Judgement (says "You Can't Do That Yet")

> Haven't got "Seal of Dedication" abillity, im 48 lvl atm. It says i should get it at 46

**Comment by kaytotes** [comment]
```
Call stack:
Address   Frame     Function      SourceFile
00007FF9196B4A01  0000002B389FEBC0  TSAura::GetEffect+51  tswow\tswow-core\Private\TSAura.cpp line 391
00007FF91E93BAB0  0000002B389FED10  <lambda_31537183a08061d58dc2ec357f89e69d>::operator()<TSSpell,TSMutable<unsigned int,double>,TSSpellDamageInfo,double,bool,double>+470  modules\project-epoch\epoch\livescripts\build\project-epoch.dataset\cpp\livescripts\classes\paladin\seal-of-dedication.cpp line 41
```

Fyi, wasn't resolved in beta.

**Comment by ghost** [comment]
Fixed in https://github.com/Project-Epoch/epoch-core/pull/1494 (hopefully anyway)

**Comment by Shadownflame** [comment]
Judgment no longer fails. Seal of Dedication and Judgment of Dedication still don't proc Vengeance.

**Comment by kaytotes** [comment]
Next deploy.

Note that when Dedication chains to a target that _also_ has a chance to proc. Same with the wave. This is a feature not a bug.

**Comment by Hatson22** [comment]
Both the passive Seal chain and Judgement cone crits properly proc Vengeance now.

<img width="466" height="55" alt="Image" src="https://github.com/user-attachments/assets/b70f3ef6-81c1-4779-9b82-4dd2d3b7e53a" />

<img width="470" height="130" alt="Image" src="https://github.com/user-attachments/assets/5bfefd29-1835-4c2e-8b4d-564de365f94c" />
