### ISSUE TITLE
The quest complete description for the quest "Brewing Brethren" ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4236]
> The quest complete description for the quest "Brewing Brethren" (turned in at Murun Goldroar) has typos.

"What's that <playername>?" - missing comma before the player's name.

"That's my families crest aye" - family's* (possessive, not plural), as well as a missing comma before the "aye".

.go xyz -8639.920000 -545.787000 145.194000 0 4.851740

**Comment by Kestrana** [comment]
Fixed in https://github.com/Project-Epoch/epoch-core/pull/1514

**Comment by Shadownflame** [comment]
Comma still missing both after "what's that" and in the introduction text after "how on azeroth did you get up here" before playername.
There is also a typo in the follow up quest No Regrets! Well Maybe Some (ID 26158) it reads "seeking riches in this here valley" is probably meant to be "seeking riches here in this valley"
And upon handing in at Dromul, it is missing a comma before "eh?"

**Comment by Kestrana** [comment]
"in this here valley" is intended colloquial speech. Same with "Me and my brother..." which would grammatically be "My brother and I" but is retained for a folksy feel to the speech.
Commas added.
