### ISSUE TITLE
Quest Pleading to Return has typos. Quest blurb reads, "Collect ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6541]
> Quest Pleading to Return has typos. Quest blurb reads, "Collect 4 Storming Essence's from Whirlwind Stormwalker's." Storming Essences and Whirlwind Stormwalkers should not be possessive. Should read "Collect 4 Storming Essences from Whirlwind Stormwalkers

.go xyz -1649.990000 2788.410000 112.355000 1 1.769090

**Comment by zana244** [comment]
Both quests in the series have the same typo.
Quest IDs 26742 and 26743
the items should be plural, but without possessive apostrophe. (Capacitive Horns, Elder Thunder Lizards, Storming Essences, Whirlwind Stormwalkers). Someone also mentioned northeast instead of north east, guess american vs british spelling? could maybe do north-east with hypen.

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514

**Comment by Shadownflame** [comment]
Quest 26743 is now correct
Quest 26742 is still having some issues: "Essence's" should be "Essences" and "Stormwalker's" should be "Stormwalkers"
northeast is now correctly northeast in the objective (north-east is the british version that is not used in WOW texts, 'north east' is grammatically incorrect), however in the quest text is still 'north east' - considering it's a troll speaking, I'm not sure if this was left on purpose to showcase their bad English
![WoWScrnShot_072524_205809](https://github.com/user-attachments/assets/d6b3b3e5-d24e-4c98-bc57-abc3a6d6f3b1)
