### ISSUE TITLE
Auction House full scan is lagging and not working as intended

### ISSUE THREAD

**Issue by SilverSaw** [Project-Epoch/bugtracker#8650]
It seems like not only on Kezan, but also on Menethil and Gurba. 

Since the 25th of Aug, full scan started lagging as hell, and I am waiting on average between 5 and 9 minutes for the addon to finish it.

<img width="337" height="110" alt="Image" src="https://github.com/user-attachments/assets/aaccc7fc-c184-48c0-8a57-5d5958155c8b" />

<img width="443" height="71" alt="Image" src="https://github.com/user-attachments/assets/23e13a94-537f-49e7-997d-8f85491bb7a0" />

<img width="278" height="56" alt="Image" src="https://github.com/user-attachments/assets/10c2fa2e-7544-4624-a18a-41ff56a3c655" />

<img width="454" height="194" alt="Image" src="https://github.com/user-attachments/assets/6c5fac3d-ec3d-43a5-b23b-d08620e80fa6" />

Also, after this server update affecting AH, when I enter the world, it is waiting 5 minutes before my quest requirement initialize, unitll then they look like this in the quest log:

<img width="195" height="41" alt="Image" src="https://github.com/user-attachments/assets/bf14f170-ded9-4a98-96bf-b149d7bbf4b0" />

**Comment by Nokhal** [comment]
Looks fixed now

**Comment by SilverSaw** [comment]
> Looks fixed now

No, it is not fixed. took me 5 mins today, and in the last days it has still been varying from 4 to 9 mins. Many people still complain in Discord.

**Comment by Gazeshooter** [comment]
I'm able to scan around 10 pages at 1-2 seconds per page until it goes up to 10 seconds per page

<img width="352" height="164" alt="Image" src="https://github.com/user-attachments/assets/3147bbee-9114-4f23-8d35-b046ea789e13" />

<img width="328" height="146" alt="Image" src="https://github.com/user-attachments/assets/bec34809-06f3-438a-854e-142cfa85905c" />
